# Site settings
title: Personal Website Liu
email: liuyang570926881@gmail.com
description: > liu946, IT, thought, blog,
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://liu946.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  liu946

# Build settings
markdown: kramdown

highlighter: pygments

paginate: 10